version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx_vue
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php

    php:
        build: ./docker/php
        container_name: php_vue
        volumes:
            - ./src:/var/www/

    mysql:
        image: mysql:8.0.26
        container_name: mysql_vue
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_vue_db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin_vue
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=pass
        depends_on:
            - mysql
        ports:
            - 8080:80

    node:
        image: node:14.18-alpine
        container_name: node_vue
        # コンテナ内の標準出力とホストの出力を設定：trueを指定
        tty: true
        # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
        volumes:
            - ./src:/var/www
        # コンテナ起動後のカレントディレクトリを設定
        working_dir: /var/www